---
- name: Login test
  hosts: all
  gather_facts: no
  vars:
    User1: "User1"
    User2: "User2"
    User3: "User3"
    User1_pass: "{{ User1_pass }}"
    User2_pass: "{{ User2_pass }}"
    User3_pass: "{{ User3_pass }}"
  
  tasks:
    - name: Test for User1
      ansible.builtin.shell: |
        echo "{{ User1_pass }}" | sshpass -p {{ User1_pass }} ssh -o StrictHostKeyChecking=no {{ item }}@{{ inventory_hostname }} exit
      with_items: "{{ User1 }}"
      register: login_results
      ignore_errors: yes

    - name: Test for User2
      ansible.builtin.shell: |
        echo "{{ User2_pass }}" | sshpass -p {{ User2_pass }} ssh -o StrictHostKeyChecking=no {{ item }}@{{ inventory_hostname }} exit
      with_items: "{{ User2 }}"
      register: login_results
      ignore_errors: yes 
    
    - name: Test for User3
      ansible.builtin.shell: |
        echo "{{ User3_pass }}" | sshpass -p {{ User3_pass }} ssh -o StrictHostKeyChecking=no {{ item }}@{{ inventory_hostname }} exit
      with_items: "{{ User3 }}"
      register: login_results
      ignore_errors: yes 
  
    - name: Show result
      ansible.builtin.debug:
        msg: "Wynik logowania dla {{ item.item }}: {{ item.rc }}"
      with_items: "{{ login_results.results }}"
