---
- name: Password Change for RHEL9+ Blue Brands
  hosts: bilka:salling:br:fotex:cjr:starbucks
  gather_facts: no

  vars_files:
    - group_vars/all/vault.yml

  vars:
    current_time: "{{ lookup('pipe', 'date +\"%Y-%m-%dT%H:%M:%S\"') }}"

  tasks:
    - name: Check if host is reachable
      ansible.builtin.ping:
      register: ping_result
      ignore_unreachable: yes
      ignore_errors: yes

    - name: Log unreachable hosts
      when: ping_result.unreachable is defined and ping_result.unreachable > 0
      ansible.builtin.lineinfile:
        create: yes
        insertafter: EOF
        path: "/home/kuba/repos/yamle/rhel_password_change/pass_change_errors"
        line: |
          {{ current_time }} - Host: {{ inventory_hostname }} Error: Host unreachable
      delegate_to: localhost
    
    - block:
      - name: check if k511 exist
        ansible.builtin.shell: id -u k511
        register: user_exists
        ignore_errors: yes

      - name: Change password for k511
        ansible.builtin.user:
          name: "k511"
          password: "{{ k511 | password_hash('sha512') }}"
          update_password: always
        when: user_exists.rc == 0
        register: password_change_result
      
      rescue:
        - name: Log errors from password change
          ansible.builtin.lineinfile:
            create: yes
            insertafter: EOF
            path: "/home/kuba/repos/yamle/rhel_password_change/pass_change_errors"
            line: |
              {{ current_time }} - Host: {{ inventory_hostname }} - User: k511 - Error: {{ ansible_failed_result.msg }}
      
          delegate_to: localhost
      
      always:
        - name: Log all information
          ansible.builtin.lineinfile:
            create: yes
            insertafter: EOF
            path: "/home/kuba/repos/yamle/rhel_password_change/pass_change_logs"
            line: |
              {{ current_time }} - Host: {{ inventory_hostname }} - User: k511 - Password change: {{ 'SUCCESS' if password_change_result is defined and password_change_result.changed else 'ERROR' }}
          delegate_to: localhost
    
    - block:
      - name: check if bdb exist
        ansible.builtin.shell: id -u bdb
        register: user_exists
        ignore_errors: yes

      - name: Change password for bdb
        ansible.builtin.user:
          name: "bdb"
          password: "{{ bdb | password_hash('sha512') }}"
          update_password: always
        when: user_exists.rc == 0
        register: password_change_result
      
      rescue:
        - name: Log errors from password change
          ansible.builtin.lineinfile:
            create: yes
            insertafter: EOF
            path: "/home/kuba/repos/yamle/rhel_password_change/pass_change_errors"
            line: |
              {{ current_time }} - Host: {{ inventory_hostname }} - User: bdb - Error: {{ ansible_failed_result.msg }}
      
          delegate_to: localhost
      
      always:
        - name: Log all information
          ansible.builtin.lineinfile:
            create: yes
            insertafter: EOF
            path: "/home/kuba/repos/yamle/rhel_password_change/pass_change_logs"
            line: |
              {{ current_time }} - Host: {{ inventory_hostname }} - User: bdb - Password change: {{ 'SUCCESS' if password_change_result is defined and password_change_result.changed else 'ERROR' }}
          delegate_to: localhost
    
    - block:
      - name: check if supprw exist
        ansible.builtin.shell: id -u supprw
        register: user_exists
        ignore_errors: yes

      - name: Change password for supprw
        ansible.builtin.user:
          name: "supprw"
          password: "{{ supprw | password_hash('sha512') }}"
          update_password: always
        when: user_exists.rc == 0
        register: password_change_result
      
      rescue:
        - name: Log errors from password change
          ansible.builtin.lineinfile:
            create: yes
            insertafter: EOF
            path: "/home/kuba/repos/yamle/rhel_password_change/pass_change_errors"
            line: |
              {{ current_time }} - Host: {{ inventory_hostname }} - User: supprw - Error: {{ ansible_failed_result.msg }}
      
          delegate_to: localhost
      
      always:
        - name: Log all information
          ansible.builtin.lineinfile:
            create: yes
            insertafter: EOF
            path: "/home/kuba/repos/yamle/rhel_password_change/pass_change_logs"
            line: |
              {{ current_time }} - Host: {{ inventory_hostname }} - User: supprw - Password change: {{ 'SUCCESS' if password_change_result is defined and password_change_result.changed else 'ERROR' }}
          delegate_to: localhost

    - block:
      - name: check if suppro exist
        ansible.builtin.shell: id -u suppro
        register: user_exists
        ignore_errors: yes

      - name: Change password for suppro
        ansible.builtin.user:
          name: "suppro"
          password: "{{ suppro | password_hash('sha512') }}"
          update_password: always
        when: user_exists.rc == 0
        register: password_change_result
      
      rescue:
        - name: Log errors from password change
          ansible.builtin.lineinfile:
            create: yes
            insertafter: EOF
            path: "/home/kuba/repos/yamle/rhel_password_change/pass_change_errors"
            line: |
              {{ current_time }} - Host: {{ inventory_hostname }} - User: suppro - Error: {{ ansible_failed_result.msg }}
      
          delegate_to: localhost
      
      always:
        - name: Log all information
          ansible.builtin.lineinfile:
            create: yes
            insertafter: EOF
            path: "/home/kuba/repos/yamle/rhel_password_change/pass_change_logs"
            line: |
              {{ current_time }} - Host: {{ inventory_hostname }} - User: suppro - Password change: {{ 'SUCCESS' if password_change_result is defined and password_change_result.changed else 'ERROR' }}
          delegate_to: localhost
    
    - block:
      - name: check if tomra exist
        ansible.builtin.shell: id -u tomra
        register: user_exists
        ignore_errors: yes

      - name: Change password for tomra
        ansible.builtin.user:
          name: "tomra"
          password: "{{ tomra | password_hash('sha512') }}"
          update_password: always
        when: user_exists.rc == 0
        register: password_change_result
      
      rescue:
        - name: Log errors from password change
          ansible.builtin.lineinfile:
            create: yes
            insertafter: EOF
            path: "/home/kuba/repos/yamle/rhel_password_change/pass_change_errors"
            line: |
              {{ current_time }} - Host: {{ inventory_hostname }} - User: tomra - Error: {{ ansible_failed_result.msg }}
      
          delegate_to: localhost
      
      always:
        - name: Log all information
          ansible.builtin.lineinfile:
            create: yes
            insertafter: EOF
            path: "/home/kuba/repos/yamle/rhel_password_change/pass_change_logs"
            line: |
              {{ current_time }} - Host: {{ inventory_hostname }} - User: tomra - Password change: {{ 'SUCCESS' if password_change_result is defined and password_change_result.changed else 'ERROR' }}
          delegate_to: localhost
    
    - block:
      - name: check if emergusr exist
        ansible.builtin.shell: id -u emergusr
        register: user_exists
        ignore_errors: yes

      - name: Change password for emergusr
        ansible.builtin.user:
          name: "emergusr"
          password: "{{ emergusr | password_hash('sha512') }}"
          update_password: always
        when: user_exists.rc == 0
        register: password_change_result
      
      rescue:
        - name: Log errors from password change
          ansible.builtin.lineinfile:
            create: yes
            insertafter: EOF
            path: "/home/kuba/repos/yamle/rhel_password_change/pass_change_errors"
            line: |
              {{ current_time }} - Host: {{ inventory_hostname }} - User: emergusr - Error: {{ ansible_failed_result.msg }}
      
          delegate_to: localhost
      
      always:
        - name: Log all information
          ansible.builtin.lineinfile:
            create: yes
            insertafter: EOF
            path: "/home/kuba/repos/yamle/rhel_password_change/pass_change_logs"
            line: |
              {{ current_time }} - Host: {{ inventory_hostname }} - User: emergusr - Password change: {{ 'SUCCESS' if password_change_result is defined and password_change_result.changed else 'ERROR' }}
          delegate_to: localhost      

    - block:
      - name: check if supphwdk exist
        ansible.builtin.shell: id -u supphwdk
        register: user_exists
        ignore_errors: yes

      - name: Change password for supphwdk
        ansible.builtin.user:
          name: "supphwdk"
          password: "{{ supphwdk | password_hash('sha512') }}"
          update_password: always
        when: user_exists.rc == 0
        register: password_change_result
      
      rescue:
        - name: Log errors from password change
          ansible.builtin.lineinfile:
            create: yes
            insertafter: EOF
            path: "/home/kuba/repos/yamle/rhel_password_change/pass_change_errors"
            line: |
              {{ current_time }} - Host: {{ inventory_hostname }} - User: supphwdk - Error: {{ ansible_failed_result.msg }}
      
          delegate_to: localhost
      
      always:
        - name: Log all information
          ansible.builtin.lineinfile:
            create: yes
            insertafter: EOF
            path: "/home/kuba/repos/yamle/rhel_password_change/pass_change_logs"
            line: |
              {{ current_time }} - Host: {{ inventory_hostname }} - User: supphwdk - Password change: {{ 'SUCCESS' if password_change_result is defined and password_change_result.changed else 'ERROR' }}
          delegate_to: localhost      
    
    - block:
      - name: check if driftdk exist
        ansible.builtin.shell: id -u driftdk
        register: user_exists
        ignore_errors: yes

      - name: Change password for driftdk
        ansible.builtin.user:
          name: "driftdk"
          password: "{{ driftdk | password_hash('sha512') }}"
          update_password: always
        when: user_exists.rc == 0
        register: password_change_result
      
      rescue:
        - name: Log errors from password change
          ansible.builtin.lineinfile:
            create: yes
            insertafter: EOF
            path: "/home/kuba/repos/yamle/rhel_password_change/pass_change_errors"
            line: |
              {{ current_time }} - Host: {{ inventory_hostname }} - User: driftdk - Error: {{ ansible_failed_result.msg }}
      
          delegate_to: localhost
      
      always:
        - name: Log all information
          ansible.builtin.lineinfile:
            create: yes
            insertafter: EOF
            path: "/home/kuba/repos/yamle/rhel_password_change/pass_change_logs"
            line: |
              {{ current_time }} - Host: {{ inventory_hostname }} - User: driftdk - Password change: {{ 'SUCCESS' if password_change_result is defined and password_change_result.changed else 'ERROR' }}
          delegate_to: localhost  

