- name: Wyświetlanie haseł z pliku Vault
  hosts: localhost
  gather_facts: no
  vars_files:
    - vault.yml

  tasks:
    - name: Wyświetlanie haseł z pliku Vault
      debug:
        msg: "Hasło użytkownika {{ item.key }}: {{ item.value }}"
      loop: "{{ vault_secrets | dict2items }}"
      vars:
        vault_secrets: "{{ lookup('file', 'vault.yml') | from_yaml }}"

