---

- name: run Python script
  hosts: all
  tasks:
    - name: run test.py script
      ansible.builtin.script:
        executable: python3
        cmd: test.py
      register: os_raw_output

    - name: print os_raw_output
      ansible.builtin.debug:
        var: os_raw_output
        verbosity: 2

    - name: convert outpot to JSON
      ansible.builtin.set_fact:
        os_list: "{{ os_raw_output.stdout | from_json }}"

    - name: print os_list:
        ansible.builtin.debug:
        var: os_list
