---
- name: Change password for User1 usign Azure secret
  hosts: all
  become: yes
  vars:
    user_to_update: "User1"
    new_password: "{{ User1_pass }}"

  tasks:

    - name: Set password for User1
      ansible.builtin.user:
        name: "{{ user_to_update }}"
        password: "{{ new_password | password_hash('sha512') }}"
      become: true
      ignore_errors: yes
