---
- name: Change password for User2 usign Azure secret
  hosts: all
  become: yes
  vars:
    user_to_update: "User2"
    new_password: "{{ User2_pass }}"

  tasks:

    - name: Set password for User2
      ansible.builtin.user:
        name: "{{ user_to_update }}"
        password: "{{ new_password | password_hash('sha512') }}"
      become: true
      ignore_errors: yes
