---
- name: Install and Configure Zabbix Agent
  hosts: all
  become: yes
  gather_facts: yes  # Ensure facts are gathered
  vars:
    zabbix_agent_version: "6.4"
    zabbix_server_ip: "192.168.1.100"  # Replace with your Zabbix server IP
    zabbix_agent_listen_port: 10050
  tasks:
    # No need to gather OS information explicitly; facts are gathered automatically

    # Add Zabbix repository and GPG key for Debian/Ubuntu systems
    - name: Add Zabbix repository on Debian/Ubuntu
      apt_repository:
        repo: "deb http://repo.zabbix.com/zabbix/{{ zabbix_agent_version }}/{{ ansible_facts.distribution | lower }} {{ ansible_facts.distribution_release | lower }} main"
        state: present
      when: ansible_facts.os_family == "Debian"

    - name: Add Zabbix GPG key on Debian/Ubuntu
      apt_key:
        url: "https://repo.zabbix.com/zabbix-official-repo.key"
        state: present
      when: ansible_facts.os_family == "Debian"

    - name: Update apt cache on Debian/Ubuntu
      apt:
        update_cache: yes
      when: ansible_facts.os_family == "Debian"

    # Add Zabbix repository for RedHat/CentOS systems
    - name: Add Zabbix repository on RedHat/CentOS
      yum_repository:
        name: zabbix
        description: "Zabbix Official Repository"
        baseurl: "https://repo.zabbix.com/zabbix/{{ zabbix_agent_version }}/rhel/{{ ansible_facts.distribution_major_version }}/$basearch/"
        gpgcheck: yes
        gpgkey: "https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591"
        enabled: yes
      when: ansible_facts.os_family == "RedHat"

    # Install Zabbix Agent on Debian/Ubuntu
    - name: Install Zabbix Agent on Debian/Ubuntu
      apt:
        name: zabbix-agent
        state: present
      when: ansible_facts.os_family == "Debian"

    # Install Zabbix Agent on RedHat/CentOS
    - name: Install Zabbix Agent on RedHat/CentOS
      yum:
        name: zabbix-agent
        state: present
      when: ansible_facts.os_family == "RedHat"

    # Backup existing Zabbix Agent configuration if it exists
    - name: Backup existing Zabbix Agent configuration
      copy:
        src: /etc/zabbix/zabbix_agentd.conf
        dest: /etc/zabbix/zabbix_agentd.conf.backup
        remote_src: yes
      when: ansible_facts.packages.get('zabbix-agent') is defined

    # Apply the new Zabbix Agent configuration from the template
    - name: Configure Zabbix Agent
      template:
        src: zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
        owner: root
        group: root
        mode: 0644

    # Ensure the Zabbix Agent service is enabled and running
    - name: Ensure Zabbix Agent service is enabled and running
      service:
        name: zabbix-agent
        state: started
        enabled: yes

    # Verify that Zabbix Agent service is running
    - name: Verify Zabbix Agent is running
      shell: systemctl is-active zabbix-agent
      register: zabbix_agent_status
      failed_when: zabbix_agent_status.stdout.strip() != "active"

    - name: Zabbix Agent service status
      debug:
        msg: "Zabbix Agent service is {{ zabbix_agent_status.stdout.strip() }}"
