---
- name: Install and Configure Zabbix Agent
  hosts: all
  become: yes
  vars:
    zabbix_agent_version: "6.4"
    zabbix_server_ip: "192.168.1.100"  # Replace with your Zabbix server IP
    zabbix_agent_listen_port: 10050
  tasks:
    # Determine the operating system family and distribution details
    - name: Gather OS family and distribution information
      ansible.builtin.setup:
        gather_subset:
          - "ansible_os_family"
          - "ansible_distribution"
          - "ansible_distribution_major_version"
          - "ansible_distribution_release"
      register: os_info

    # Add Zabbix repository for RedHat/CentOS systems
    - name: Add Zabbix repository on RedHat/CentOS
      ansible.builtin.dnf_repository:
        name: zabbix
        description: "Zabbix Official Repository"
        baseurl: "https://repo.zabbix.com/zabbix/{{ zabbix_agent_version }}/rhel/{{ ansible_facts.distribution_major_version }}/$basearch/"
        gpgcheck: yes
        gpgkey: "https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591"
        enabled: yes
      when: os_info.ansible_facts.ansible_os_family == "RedHat"

    # Check if Zabbix Agent is already installed
    - name: Gather installed packages facts
      ansible.builtin.package_facts:

    # Install Zabbix Agent on RedHat/CentOS if not installed
    - name: Install Zabbix Agent on RedHat/CentOS
      ansible.builtin.dnf:
        name: zabbix-agent
        state: present
      when:
        - os_info.ansible_facts.ansible_os_family == "RedHat"
        - "'zabbix-agent' not in ansible_facts.packages"

    # Check if the Zabbix Agent configuration file exists
    - name: Check for existing Zabbix Agent configuration
      ansible.builtin.stat:
        path: /etc/zabbix/zabbix_agentd.conf
      register: zabbix_conf

    # Backup existing Zabbix Agent configuration if it exists
    - name: Backup existing Zabbix Agent configuration
      ansible.builtin.copy:
        src: /etc/zabbix/zabbix_agentd.conf
        dest: /etc/zabbix/zabbix_agentd.conf.backup
        remote_src: yes
      when: zabbix_conf.stat.exists

    # Apply the new Zabbix Agent configuration from the template
    - name: Configure Zabbix Agent
      ansible.builtin.template:
        src: zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
        owner: root
        group: root
        mode: 0644

    # Ensure the Zabbix Agent service is enabled and running
    - name: Ensure Zabbix Agent service is enabled and running
      ansible.builtin.service:
        name: zabbix-agent
        state: started
        enabled: yes

    # Gather facts about services
    - name: Gather service facts
      ansible.builtin.service_facts:

    # Verify that Zabbix Agent service is running
    - name: Verify Zabbix Agent is running
      ansible.builtin.fail:
        msg: "Zabbix Agent service is not running."
      when:
        - ansible_facts.services['zabbix-agent'].state != 'running'
