---
- name: Install and Configure Zabbix Agent
  hosts: all
  become: yes
  gather_facts: yes  
  vars:
    zabbix_agent_version: "6.4"
    zabbix_server_ip: "192.168.1.100"  
    zabbix_agent_listen_port: 10050
  tasks:

    - name: Add Zabbix repository on RedHat/CentOS
      yum_repository:
        name: zabbix
        description: "Zabbix Official Repository"
        baseurl: "https://repo.zabbix.com/zabbix/{{ zabbix_agent_version }}/rhel/{{ ansible_facts.distribution_major_version }}/$basearch/"
        gpgcheck: yes
        gpgkey: "https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591"
        enabled: yes
      when: ansible_facts.os_family == "RedHat"

    - name: Install Zabbix Agent on RedHat/CentOS
      yum:
        name: zabbix-agent
        state: present
      when: ansible_facts.os_family == "RedHat"

    - name: Check if Zabbix Agent configuration file exists
      stat:
        path: /etc/zabbix/zabbix_agentd.conf
      register: zabbix_conf

    - name: Backup existing Zabbix Agent configuration
      copy:
        src: /etc/zabbix/zabbix_agentd.conf
        dest: /etc/zabbix/zabbix_agentd.conf.backup
        remote_src: yes
      when: zabbix_conf.stat.exists

    - name: Configure Zabbix Agent
      template:
        src: zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
        owner: root
        group: root
        mode: '0644'

    - name: Ensure Zabbix Agent service is enabled and running
      service:
        name: zabbix-agent
        state: started
        enabled: yes
