---
- name: Instalacja Dockera i wdrożenie aplikacji Flask
  hosts: all
  become: yes
  vars:
    app_dir: /opt/flask_app
  tasks:

  - name: Instalacja niezbędnych pakietów
    yum:
      name:
        - yum-utils
      state: present

  - name: Dodanie repozytorium Dockera
    yum_repository:
      name: docker-ce-stable
      description: Docker CE Stable - $basearch
      baseurl: https://download.docker.com/linux/centos/9/$basearch/stable
      enabled: yes
      gpgcheck: yes
      gpgkey: https://download.docker.com/linux/centos/gpg

  - name: Instalacja Docker CE
    yum:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present

  - name: Uruchomienie i włączenie usługi Dockera
    service:
      name: docker
      state: started
      enabled: yes

  - name: Dodanie użytkownika do grupy docker
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes

  - name: Utworzenie katalogu aplikacji
    file:
      path: "{{ app_dir }}"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"

  - name: Skopiowanie plików aplikacji
    copy:
      src: files/
      dest: "{{ app_dir }}/"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0755'

  - name: Budowanie obrazu Dockera
    shell: |
      docker build -t flask_app {{ app_dir }}
    args:
      chdir: "{{ app_dir }}"
    become: yes

  - name: Uruchomienie kontenera Dockera
    shell: |
      docker run -d --name flask_app_container -p 80:80 --restart always flask_app
    become: yes
