---
- name: Install Docker and run flask app
  hosts: all
  become: yes
  vars:
    app_dir: /opt/flask_app
  tasks:

  - name: Add Docker repository
    yum_repository:
      name: docker-ce-stable
      description: Docker CE Stable - $basearch
      baseurl: https://download.docker.com/linux/centos/9/$basearch/stable
      enabled: yes
      gpgcheck: yes
      gpgkey: https://download.docker.com/linux/centos/gpg

  - name: Install Docker CE
    yum:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present

  - name: Start and enable Docker service
    service:
      name: docker
      state: started
      enabled: yes

  - name: Add User to docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes

  - name: Create app directory
    file:
      path: "{{ app_dir }}"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"

  - name: Copy app files
    copy:
      src: files/
      dest: "{{ app_dir }}/"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0755'

  - name: Build Image
    shell: |
      docker build -t flask_app {{ app_dir }}
    args:
      chdir: "{{ app_dir }}"
    become: yes

  - name: Run Container
    shell: |
      docker run -d --name flask_app_container -p 80:80 --restart always flask_app
    become: yes
